# Generated by Django 3.1.4 on 2021-01-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www_bank', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='message_to_admin',
            field=models.TextField(default='My message to admin'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
